//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaNET_CesarGayo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoSet()
        {
            this.ProductoSet = new HashSet<ProductoSet>();
        }
    
        public int Id { get; set; }
        public string Fecha { get; set; }
        public string Completado { get; set; }
        public int Usuario_Id { get; set; }
        public string Property1 { get; set; }
    
        public virtual UsuarioSet UsuarioSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoSet> ProductoSet { get; set; }
    }
}
